Repository HRocketRaccoon/HRaccoon-front, pull requests merged in 2024-06, with the labels that each got.

#4 [#3] 공통 컴포넌트 기능 구현
  package-lock.json
  package.json
  src/components/apexchart/ApexChart.vue
  src/components/calendar/PickerCalendar.vue
  src/components/calendar/TeamCalendar.vue
  src/views/dev/TestView.vue
Labels: 컴포넌트

#6 [#5] 결재 관련 UI 기능 추가 및 axios 설정
  .eslintrc.cjs
  package-lock.json
  package.json
  src/api/axios.js
  src/components/table/ApprovalTable.vue
  src/layouts/components/DefaultLayoutWithVerticalNav.vue
  src/main.js
  src/plugins/toastification/toastOption.js
  src/plugins/vuetify/vuetify.js
  src/router/index.js
  src/stores/useAuthStore.js
  src/views/approval/ApprovalDetailView.vue
  src/views/approval/ApprovalStatusListView.vue
  src/views/approval/RequestApprovalListView.vue
  src/views/approval/RequestApprovalView.vue
  src/views/auth/LoginView.vue
  src/views/dev/TestView.vue
  vite.config.js
Labels: 컴포넌트, 기능 구현

#5 [#4] homePage 구현 및 backend 연결
  package.json
  src/api/axios.js
  src/assets/circle-substract.png
  src/components/apexchart/ApexChart.vue
  src/components/calendar/PickerCalendar.vue
  src/components/remainseat/RemainSeat.vue
  src/components/todo/TodoList.vue
  src/components/todo/TodoModal.vue
  src/plugins/vuetify/theme.js
  src/router/index.js
  src/views/home/HomeView.vue
  vite.config.js
Labels: 컴포넌트, 기능 구현

#8 [#7] 직원 정보 조회 페이지 구현
  src/components/calendar/PickerCalendar.vue
  src/components/table/EmployeeTable.vue
  src/layouts/components/DefaultLayoutWithVerticalNav.vue
  src/router/index.js
  src/views/search/EmployeeSearch.vue
Labels: 컴포넌트, 기능 구현

#9 feat: ApexChart and Calendar 컴포넌트화
  src/components/apexchart/ApexChart.vue
  src/components/apexchart/ApprovalChartCard.vue
  src/components/calendar/CalendarCard.vue
  src/components/calendar/TeamCalendar.vue
  src/components/calendar/VueDatePicker.vue
  src/components/remainseat/RemainSeat.vue
  src/views/home/HomeView.vue
  src/views/search/EmployeeSearch.vue
Labels: 컴포넌트, 기능 구현

#10 [#9] 홈 페이지 백엔드 연동 ( ApexChart and TeamCalendar )
  src/components/apexchart/ApexChart.vue
  src/components/apexchart/ApprovalChartCard.vue
  src/components/calendar/CalendarCard.vue
  src/components/table/EmployeeTable.vue
  src/components/todo/TodoList.vue
  src/stores/useCodeStore.js
Labels: 기능 구현

#11 [#10] 공통 컴포넌트 및 근태 관리 페이지 구현
  package.json
  src/components/apexchart/AttendanceApexChart.vue
  src/components/attendance/CardNavigation.vue
  src/components/attendance/WorkTime.vue
  src/components/dialog/OneButtonDialog.vue
  src/components/dialog/TwoButtonDialog.vue
  src/components/table/ApprovalTable.vue
  src/layouts/components/DefaultLayoutWithVerticalNav.vue
  src/layouts/components/UserProfile.vue
  src/main.js
  src/router/index.js
  src/views/approval/ApprovalDetailView.vue
  src/views/attendance/AttendanceView.vue
  src/views/auth/LoginView.vue
  src/views/dev/TestView.vue
Labels: 컴포넌트, 기능 구현

#12 [#11] 로그인 로그아웃 로직 수정
  package-lock.json
  package.json
  src/api/axios.js
  src/components/calendar/CalendarCard.vue
  src/components/dialog/ChildDialog.vue
  src/components/dialog/NoButtonDialog.vue
  src/components/remainseat/RemainSeat.vue
  src/layouts/components/DefaultLayoutWithVerticalNav.vue
  src/layouts/components/UserProfile.vue
  src/router/index.js
  src/stores/useAuthStore.js
  src/util/constants/loginConstant.js
  src/util/util.js
  src/views/auth/LoginView.vue
  src/views/home/HomeView.vue
Labels: 오류

#13 [#12] 직원 정보 단건 조회 기능 페이지 추가
  src/components/apexchart/ApexChart.vue
  src/components/calendar/CalendarCard.vue
  src/components/remainseat/RemainSeat.vue
  src/components/search/EmployeeTable.vue
  src/components/search/EmployeeView.vue
  src/components/table/EmployeeTable.vue
  src/router/index.js
  src/stores/useCodeStore.js
  src/views/home/HomeView.vue
  src/views/search/EmployeeSearch.vue
Labels: 기능 구현

#15 [#13] 직원 검색 및 todo 오류 수정
  src/components/apexchart/ApprovalChartCard.vue
  src/components/search/EmployeeTable.vue
  src/components/search/EmployeeView.vue
  src/components/todo/TodoList.vue
  src/components/todo/TodoModal.vue
  src/router/index.js
  src/views/search/EmployeeSearch.vue
Labels: 오류

#16 [#14] Todo 오류 수정
  src/components/todo/TodoList.vue
  src/views/search/EmployeeSearch.vue
Labels: 오류

#14 [#7] 좌석 백엔드 연동(좌석 선택, 취소)
  src/stores/useCodeStore.js
  src/stores/useSeatStore.js
  src/styles/styles.scss
  src/views/SeatView.vue
Labels: 기능 구현

#21 [#18] 퇴사 사유 미기입 오류 및 직책, 직위 자리 바뀜 오류 수정
  src/components/admin/AdminEmployeeView.vue
Labels: 오류

#23 [BUILD] Deploy to main ver 0.0.3
  .github/workflows/deploy.yml
  package-lock.json
  package.json
  src/@core/components/cards/CardStatisticsVertical.vue
  src/@layouts/components/VerticalNav.vue
  src/assets/images/cards/chart-info.png
  src/assets/images/cards/chart-success.png
  src/assets/images/cards/credit-card-primary.png
  src/assets/images/cards/credit-card-success.png
  src/assets/images/cards/credit-card-warning.png
  src/assets/images/cards/illustration-john-dark.png
  src/assets/images/cards/illustration-john-light.png
  src/assets/images/cards/wallet-info.png
  src/assets/images/cards/wallet-primary.png
  src/assets/images/hraccoon_primary.png
  src/assets/json/background.json
  src/assets/json/landing.json
  src/components/CardNavigation.vue
  src/components/GraphBar.vue
  src/components/WorkTime.vue
  src/components/apexchart/ApexChart.vue
  src/components/calendar/CalendarCard.vue
  src/components/calendar/VueDatePicker.vue
  src/components/dashboard/AnalyticsCongratulations.vue
  src/components/dialog/TwoInputDialog.vue
  src/components/remainseat/RemainSeat.vue
  src/components/table/AdminEmployeeTable.vue
  src/layouts/components/DefaultLayoutWithVerticalNav.vue
  src/plugins/aws/s3.js
  src/router/index.js
  src/styles/styles.scss
  src/views/admin/AdminEmployeeSearch.vue
  src/views/admin/AdminEmployeeView.vue
  src/views/admin/EmployeeRegisterView.vue
  src/views/attendance/AttendanceView.vue
  src/views/auth/LoginView.vue
  src/views/dev/TestView.vue
  src/views/home/HomeView.vue
Labels: ci/cd
