Repository HRocketRaccoon/HRaccoon-front, pull requests merged in 2024-07, with the labels that each got.

#25 [BUILD] Deploy to main ver 0.0.4
  src/@core/components/cards/CardStatisticsVertical.vue
  src/components/remainseat/RemainSeat.vue
  src/router/index.js
  src/views/attendance/AttendanceView.vue
  src/views/home/HomeView.vue
Labels: ci/cd

#26 [BUILD] Deploy to main ver 0.0.5
  src/views/user/MypageView.vue
Labels: ci/cd

#28 [BUILD] Deploy to main ver 0.0.6
  src/router/index.js
  src/views/admin/AdminEmployeeSearch.vue
  src/views/admin/AdminEmployeeView.vue
  src/views/admin/EmployeeRegisterView.vue
  src/views/search/EmployeeSearch.vue
  src/views/search/EmployeeView.vue
  src/views/user/MypageView.vue
Labels: ci/cd

#29 [BUILD] Deploy to main ver 1.0.0
  src/views/admin/AdminEmployeeView.vue
  src/views/attendance/AttendanceView.vue
  src/views/search/EmployeeView.vue
Labels: ci/cd

#32 [#23] 홈 잔여 좌석 조회 구현
  src/views/home/HomeView.vue
Labels: 기능 구현

#33 [#24] 비밀번호 타입 password
  src/components/dialog/ThreeInputDialog.vue
  src/components/dialog/TwoInputDialog.vue
Labels: 성능 개선

#34 [BUILD] Deploy to main ver 1.0.1
  src/components/dialog/ThreeInputDialog.vue
  src/components/dialog/TwoInputDialog.vue
  src/views/home/HomeView.vue
Labels: ci/cd
